
env:
   global:
     - CONAN_REFERENCE: "tinyxml2/7.1.0"
     - CONAN_USERNAME: "nicolastagliani"
     - CONAN_LOGIN_USERNAME: "nicolastagliani"
     - CONAN_UPLOAD: "https://api.bintray.com/conan/nicolastagliani/tinyxml2"
     - CONAN_CHANNEL: "testing"
     - CONAN_STABLE_BRANCH_PATTERN: "stable/*"
     - CONAN_UPLOAD_ONLY_WHEN_STABLE: 1

osx: &osx
   os: osx
   language: generic
matrix:
   include:
      - <<: *osx
        osx_image: xcode7.3
        env: CONAN_APPLE_CLANG_VERSIONS=7.3

      - <<: *osx
        osx_image: xcode8.3
        env: CONAN_APPLE_CLANG_VERSIONS=8.1

      - <<: *osx
        osx_image: xcode9.2
        env: CONAN_APPLE_CLANG_VERSIONS=9.0

      - <<: *osx
        osx_image: xcode9.3
        env: CONAN_APPLE_CLANG_VERSIONS=9.1

      - <<: *osx
        osx_image: xcode10
        env: CONAN_APPLE_CLANG_VERSIONS=10.0

install:
  - chmod +x .travis/install.sh
  - ./.travis/install.sh

script:
  - chmod +x .travis/run.sh
  - ./.travis/run.sh
